#!/usr/bin/env ruby

#
# Copyright (c) 2017-2017, John Mettraux, jmettraux@gmail.com
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
#
# Made in Japan
#

require 'json'

TYPE_SPEED = 0.077
WAIT_SPEED = 1.000

j = JSON.parse(
  if ARGV.empty? || ARGV == [ '-' ]
    STDIN.read
  else
    File.read(ARGV.first)
  end)

so = j
  .delete('stdout')
so = so
  .collect { |t, s|
    s.length == 1 ? [ TYPE_SPEED, s ] : [ [ t, WAIT_SPEED ].min, s ] }

loop do
  i = so.index { |t, s| s == "\b\u001b[K" }
  break unless i
  so.delete_at(i)
  so.delete_at(i - 1)
end

puts '{'
j.each { |k, v| puts "  #{k.inspect}: #{JSON.dump(v)}," }
puts '  "stdout": ['
so[0..-2].each { |o| puts "    #{JSON.dump(o)}," }
puts "    #{JSON.dump(so.last)}"
puts "  ]"
puts '}'

